### ISSUE TITLE
Add feature: Juz List

### ISSUE THREAD

**Issue by husayt** [islamic-network/api.alquran.cloud#14]
Would be nice to have something like this: `http://api.alquran.cloud/juz/`, which would have list of all juz with beginning and end e.g.

```
[
   {"juz":"1","start":"1:1","end":"2.141"},
   {"juz":"2","start":"2:142","end":"2.252"},
.....
]
```
JZK for this amazing work.

**Comment by husayt** [comment]
Also, would be very useful to have the same for manzils

**Comment by papasmile** [comment]
It appear that information (except juz) is already available on https://api.alquran.cloud/v1/meta

Just need to add a list of 'juzes'.

**Comment by meezaan** [comment]
@husayt Does the /v1/meta endpoint work for you? It isn't documented so I will add it to the docs on https://alquran.cloud/api.

**Comment by husayt** [comment]
@meezaan that is great.
Alternatively, it might be also convenient to get quran-meta as js functions and without calling apis.

[Here](https://github.com/quran-center/quran-meta) is the library we have built and use live projects.  Hope might be of use
