### ISSUE TITLE
What collation to use for arabic in database?

### ISSUE THREAD

**Issue by kickthemooon** [islamic-network/api.alquran.cloud#15]
May Allah reward you with Jannah Firdaws for the api.

I am having problems when importing the arabic ayat text from the api into my database.

Example surah Ash-Shams...

api:
وَالشَّمْسِ وَضُحَاهَا

in my database:
وَٱلشَّمْسِ وَضُحَىٰهَا

the problem is with the the Haa Haa in Duhaahaa, specifically with the first Haa in Duhaahaa.

I dont know what the problem is but i am thinking it has something to do with the collation my database is using (charset: utf8mb4; collation: utf8mb4_unicode_ci).

So I was wondering what collation are you using?

And do you know what the problem here is?

JazakAllah Khair.

**Comment by meezaan** [comment]
Alaykum Salaam brother.

What edition are you using?
