### ISSUE TITLE
How to render Tajweed text  that I get from api 

### ISSUE THREAD

**Issue by MahmoudMabrok** [islamic-network/api.alquran.cloud#20]
here for example 
`http://api.alquran.cloud/v1/surah/114/quran-tajweed
`
i got  
`
ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ [h:14688[ٱ][l[ل][g[نّ][p[َا]سِ
`
how to render it into text to use it in TextView

**Comment by meezaan** [comment]
Al Salaamu Alaykum. See https://alquran.cloud/tajweed-guide.

**Comment by MahmoudMabrok** [comment]
is there a way to render in java to be used in android?

**Comment by meezaan** [comment]
I have not written one and am not aware of one.

**Comment by haroonkhankhattak** [comment]
still no tajweed solution for android ?

**Comment by haroonkhankhattak** [comment]
> is there a way to render in java to be used in android?

yeah 
just change each css class name with the color and parse it in textview like this 
it works for me

binding.text.setText(HtmlCompat.fromHtml(      "۞ ٱللَّهُ نُورُ <font color=#AAAAAA>ٱ</font><font color=#AAAAAA>ل</font>سَّمَ<font color=#537FFF>ـٰ</font>و<font color=#537FFF>َٲ</font>تِ وَ<font color=#AAAAAA>ٱ</font>لْأَرْضِ‌ۚ مَثَلُ نُورِه<font color=#537FFF>ِۦ</font> كَمِشْكَ<font color=slnt>و</font><font color=#537FFF>ٲ</font><font color= #9400A8>ةٍ ف</font>ِيهَا مِصْبَاحٌ‌ۖ <font color=#AAAAAA>ٱ</font>لْمِصْبَاحُ فِى زُجَاجَةٍ‌ۖ <font color=#AAAAAA>ٱ</font><font color=#AAAAAA>ل</font>زُّجَاجَةُ كَأَ<font color=#FF7E1E>نّ</font>َهَا كَوْكَ<font color= #9400A8>بٌ د</font>ُرِّ<font color=#169200>ىٌّ ي</font>ُوقَدُ مِ<font color= #9400A8>ن ش</font>َجَرَ<font color=#169200>ةٍ م</font>ُّبَ<font color=#537FFF>ـٰ</font>رَكَ<font color= #9400A8>ةٍ ز</font>َيْتُونَ<font color= #169200>ةٍ ل</font>َّا شَرْقِيَّ<font color=#169200>ةٍ و</font>َلَا غَرْبِيَّ<font color=#169200>ةٍ ي</font>َكَادُ زَيْتُهَا يُض<font color=#4050FF>ِى</font>ٓءُ وَلَوْ لَمْ تَمْسَسْهُ نَا<font color=#169200>رٌ‌ۚ ن</font>ُّورٌ عَلَىٰ نُو<font color=#169200>رٍ‌ۗ ي</font>َهْدِى <font color=#AAAAAA>ٱ</font>للَّهُ لِنُورِه<font color=#537FFF>ِۦ</font> م<font color=#169200>َن ي</font>َش<font color=#4050FF>َا</font>ٓءُ‌ۚ وَيَضْرِبُ <font color=#AAAAAA>ٱ</font>للَّهُ <font color=#AAAAAA>ٱ</font>لْأَمْثَ<font color=#537FFF>ـٰ</font>لَ لِل<font color=#FF7E1E>نّ</font>َاسِ‌ۗ وَ<font color=#AAAAAA>ٱ</font>للَّهُ بِكُلِّ شَىْءٍ عَل<font color=#4050FF>ِي</font>مٌ <span color=end>٣٥</span>"
            ,HtmlCompat.FROM_HTML_MODE_LEGACY))
