### ISSUE TITLE
Cannot start quran-app: doctrine error

### ISSUE THREAD

**Issue by faridv** [islamic-network/api.alquran.cloud#22]
I'm trying to run your project and all containers start without error except quran-app which it keeps showing me this error:

    quran-app            | /usr/local/bin/doctrineProxies.sh: line 40: vendor/bin/doctrine: No such file or directory
    quran-app exited with code 127

I'm using Docker 18.9.6, build 481bc77 on Ubuntu server 18.04.2 LTS machine.

**Comment by meezaan** [comment]
Are you using docker-compose or just docker?

It appears that the vendor directory is missing. When using compose, you mount the entire volume onto the container, so if you have not run composer install locally, you don't have a vendor folder and it deletes the one in the container.

2 ways to fix it:

1. Run ```composer install``` locally and then run ```docker-compose up```.
2. SSH into the API container and just run ```composer install```.

**Comment by faridv** [comment]
Running `composer install` fixed my problem.
I think it's better to add this step in the installation instruction section.

Thank you
