### ISSUE TITLE
New English translation by Khattab

### ISSUE THREAD

**Issue by husayt** [islamic-network/api.alquran.cloud#23]
[The Clear Quran](https://theclearquran.org/) is one of the latest translations and has been endorsed by lots of scholars (see [here](https://theclearquran.org/) ). Quran.com switched to using it as a default translation. Would be great to add it here too, obviously with author's permission . 

Thanks

**Comment by meezaan** [comment]
Thank you for sharing. 

I can send them an email.

**Comment by meezaan** [comment]
@husayt FYI I've emailed them.

**Comment by meezaan** [comment]
Al Salaamu Alaykum - the author has not responded, so I will close this for now.
