### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by WebPajooh** [islamic-network/api.alquran.cloud#25]
Hi.
I was using the arabic and persian translations and tafseer books, but It's not working now.

I checked the API, and got this:
> Slim Application Error A website error has occurred. Sorry for the temporary inconvenience.

I was using your API in my telegram bot,
Please help me,
Thanks.

**Comment by meezaan** [comment]
Can you please share the URL that throws the error?

**Comment by WebPajooh** [comment]
I'm using this link:
http://api.alquran.cloud/v1/ayah/4:1/editions/ar.muhammadayyoub,fa.khorramdel

and yesterday was not working, and I got the error "Slim Application Error"
but I checked it now, And It's working (and found a new field in response "audioSecondary")

Thanks.
