### ISSUE TITLE
Add new translation by Muhamed Mehanovic

### ISSUE THREAD

**Issue by IsmetGlumcevic** [islamic-network/api.alquran.cloud#26]
Assalamu alaykum.
There is new translation for bosnian language by Muhamed Mehanovic. 
Will you add this translation to api. 
Thanks.

**Comment by IsmetGlumcevic** [comment]
Yes, I have a text of the translation and I have permission from the author to use. Can you give me the mail, please?

**Comment by meezaan** [comment]
support [at] Islamic.network.

**Comment by IsmetGlumcevic** [comment]
I send you mail.

**Comment by meezaan** [comment]
Added with the identifier ba.mehanovic.
