### ISSUE TITLE
Add an option for language direction ltr and rtl

### ISSUE THREAD

**Issue by Hissan-Dialer360** [islamic-network/api.alquran.cloud#28]
Kindly add the language direction field in the edition section, so I can change the direction of text ltr or rtl according to the language type. 

i.e rtl for ur and ltr for en.

**Comment by meezaan** [comment]
This is now done. See http://api.alquran.cloud/ayah/1/en.asad or http://api.alquran.cloud/surah/1/ur.ahmedali for instance.

**Comment by Hissan-Dialer360** [comment]
Ok, Great!
