### ISSUE TITLE
Cors origin when call api in localhost

### ISSUE THREAD

**Issue by justirva09** [islamic-network/api.alquran.cloud#30]
Hi, i using this Quran API for my web app development. the API get a CORS on network.

how to resolve this problem ?

![SSSS](https://user-images.githubusercontent.com/48151470/75112776-93dd3200-5679-11ea-8d4c-30d1951552fb.png)

**Comment by meezaan** [comment]
Setup an entry in your local host file (/etc/host on any Linux machine) with a domain that maps to 127.0.0.1.

**Comment by justirva09** [comment]
I use windows and I am implementing it using **ReactJS** with axios to get data from api. Will I have this problem if I have uploaded it to the server?

**Comment by meezaan** [comment]
Actually looking at the error, the problem is with your request. It's quite clear on the problem. Don't send the content-type header in your request and it should work just fine.

**Comment by justirva09** [comment]
oke, thanks brother :)
