### ISSUE TITLE
Where Source of Tajweed Quran

### ISSUE THREAD

**Issue by hscstudio** [islamic-network/api.alquran.cloud#32]
I have seen on database table edition that source of tajweed quran from hafidh.com, but now this site have down or for sale, where github or other project that continue this tajweeed?

**Comment by meezaan** [comment]
I don't know if the project is continued - the source was hafidh.com when the text was taken.

We know the word by word text has some issues with the way the Arabic displays so it is disabled in the API (and that too came from hafidh.com originally).

Just FYI we actually got the text from the Global Quran project, and their source was hafidh.com.
