### ISSUE TITLE
Some Juz(es) are offset by either 1 or -1

### ISSUE THREAD

**Issue by Cyberistic** [islamic-network/api.alquran.cloud#34]
Examples:

// from meta 

Juz 4 should start at {"surah":3,"ayah":92}
instead of {"surah":3,"ayah":93} 
(-1 offset)

Juz 5 should start at {"surah":5,"ayah":83} instead of {"surah":5,"ayah":82}
(+1 offset)

**Comment by meezaan** [comment]
Thank you @Cyberistic. The API matches what is on https://en.wikipedia.org/wiki/Juz%27. Do you have access to another digital source - I can't find one and short of manually checking multiple printed Qur'ans I don't really see another option to verify this.

**Comment by meezaan** [comment]
> Examples:
> 
> // from meta
> 
> Juz 4 should start at {"surah":3,"ayah":92}
> instead of {"surah":3,"ayah":93}
> (-1 offset)
> 
> Juz 5 should start at {"surah":5,"ayah":83} instead of {"surah":5,"ayah":82}
> (+1 offset)

Just for reference, the second one is Juz 7, not 5.

**Comment by Cyberistic** [comment]
Using your API:
```js
data.surahs[3].ayahs[92].page
// returns 62

data.surahs[3].ayahs[92].juz
// returns 3
```

```js
data.surahs[3].ayahs[93].page
// returns 62

data.surahs[3].ayahs[92].juz
// returns 4
```

Two ayahs in the same page can't be in different Juz-es.
Other than using your DB to check for the first ayah in the first page of each Juz, I'm not sure how this could be confirmed.

I used my own personal Quran to verify what I stated in my original issue.

> Just for reference, the second one is Juz 7, not 5. 

Whoops, sorry.
