### ISSUE TITLE
Add reciters Arabic names

### ISSUE THREAD

**Issue by RAbuBaker** [islamic-network/api.alquran.cloud#38]
Reciters names are only available in English.

Calling this API http://api.alquran.cloud/v1/edition?format=audio&language=ar&type=versebyverse :

Both name and englishName have the same value. 

![image](https://user-images.githubusercontent.com/38038348/82138202-4959f480-9827-11ea-8b5b-89b2f57fa777.png)

**Comment by vipafattal** [comment]
@meezaan 
I think this would be helpful 
```kotlin
//English names to Arabic
arrayOf(
    "Ayman Sowaid" to "د.أيمن سويد",
    "Abdul Basit" to "عبد الباسط عبد الصمد المرتل",
    "Abdul Samad" to "عبدالباسط عبدالصمد",
    "Abdullah Basfar" to "عبد الله بصفر",
    "Abdurrahmaan As-Sudais" to "عبدالرحمن السديس",
    "Abu Bakr Ash-Shaatree" to "أبو بكر الشاطري",
    "Ahmed ibn Ali al-Ajamy" to "أحمد بن علي العجمي",
    "Alafasy" to "مشاري العفاسي",
    "Hani Rifai" to "هاني الرفاعي",
    "Husary" to "محمود خليل الحصري",
    "Husary (Mujawwad)" to "محمود خليل الحصري المجود",
    "Hudhaify" to "علي بن عبدالرحمن الحذيفي",
    "Ibrahim Akhdar" to "إبراهيم الأخضر",
    "Maher Al Muaiqly" to "ماهر المعيقلي",
    "Minshawi" to "محمد صديق المنشاوي",
    "Minshawy (Mujawwad)" to "محمد صديق المنشاوي المجود",
    "Muhammad Ayyoub" to "محمد أيوب",
    "Muhammad Jibreel" to "محمد جبريل",
    "Saood bin Ibraaheem Ash-Shuraym" to "سعود الشريم"
)

//From edition to Arabic name
```kotlin
    arrayOf(
        "ar.aymanswoaid" to "د.أيمن سويد",
        "ar.abdulbasitmurattal" to "عبد الباسط عبد الصمد المرتل",
        "ar.abdulsamad" to "عبدالباسط عبدالصمد",
        "ar.abdullahbasfar" to "عبد الله بصفر",
        "ar.abdurrahmaansudais" to "عبدالرحمن السديس",
        "ar.shaatree" to "أبو بكر الشاطري",
        "ar.ahmedajamy" to "أحمد بن علي العجمي",
        "ar.alafasy" to "مشاري العفاسي",
        "ar.hanirifai" to "هاني الرفاعي",
        "ar.husary" to "محمود خليل الحصري",
        "ar.husarymujawwad" to "محمود خليل الحصري المجود",
        "ar.hudhaify" to "علي بن عبدالرحمن الحذيفي",
        "ar.ibrahimakhbar" to "إبراهيم الأخضر",
        "ar.mahermuaiqly" to "ماهر المعيقلي",
        "ar.minshawi" to "محمد صديق المنشاوي",
        "ar.minshawimujawwad" to "محمد صديق المنشاوي المجود",
        "ar.muhammadayyoub" to "محمد أيوب",
        "ar.muhammadjibreel" to "محمد جبريل",
        "ar.saoodshuraym" to "سعود الشريم"
    )
```
All Arabic names are obtained from http://mp3quran.net/.

**Comment by meezaan** [comment]
@vipafattal thank you very much! Very helpful indeed!

**Comment by RAbuBaker** [comment]
> @meezaan
> I think this would be helpful
> 
> ```kotlin
> //English names to Arabic
> arrayOf(
>     "Ayman Sowaid" to "د.أيمن سويد",
>     "Abdul Basit" to "عبد الباسط عبد الصمد المرتل",
>     "Abdul Samad" to "عبدالباسط عبدالصمد",
>     "Abdullah Basfar" to "عبد الله بصفر",
>     "Abdurrahmaan As-Sudais" to "عبدالرحمن السديس",
>     "Abu Bakr Ash-Shaatree" to "أبو بكر الشاطري",
>     "Ahmed ibn Ali al-Ajamy" to "أحمد بن علي العجمي",
>     "Alafasy" to "مشاري العفاسي",
>     "Hani Rifai" to "هاني الرفاعي",
>     "Husary" to "محمود خليل الحصري",
>     "Husary (Mujawwad)" to "محمود خليل الحصري المجود",
>     "Hudhaify" to "علي بن عبدالرحمن الحذيفي",
>     "Ibrahim Akhdar" to "إبراهيم الأخضر",
>     "Maher Al Muaiqly" to "ماهر المعيقلي",
>     "Minshawi" to "محمد صديق المنشاوي",
>     "Minshawy (Mujawwad)" to "محمد صديق المنشاوي المجود",
>     "Muhammad Ayyoub" to "محمد أيوب",
>     "Muhammad Jibreel" to "محمد جبريل",
>     "Saood bin Ibraaheem Ash-Shuraym" to "سعود الشريم"
> )
> 
> //From edition to Arabic name
> arrayOf(
>         "ar.aymanswoaid" to "د.أيمن سويد",
>         "ar.abdulbasitmurattal" to "عبد الباسط عبد الصمد المرتل",
>         "ar.abdulsamad" to "عبدالباسط عبدالصمد",
>         "ar.abdullahbasfar" to "عبد الله بصفر",
>         "ar.abdurrahmaansudais" to "عبدالرحمن السديس",
>         "ar.shaatree" to "أبو بكر الشاطري",
>         "ar.ahmedajamy" to "أحمد بن علي العجمي",
>         "ar.alafasy" to "مشاري العفاسي",
>         "ar.hanirifai" to "هاني الرفاعي",
>         "ar.husary" to "محمود خليل الحصري",
>         "ar.husarymujawwad" to "محمود خليل الحصري المجود",
>         "ar.hudhaify" to "علي بن عبدالرحمن الحذيفي",
>         "ar.ibrahimakhbar" to "إبراهيم الأخضر",
>         "ar.mahermuaiqly" to "ماهر المعيقلي",
>         "ar.minshawi" to "محمد صديق المنشاوي",
>         "ar.minshawimujawwad" to "محمد صديق المنشاوي المجود",
>         "ar.muhammadayyoub" to "محمد أيوب",
>         "ar.muhammadjibreel" to "محمد جبريل",
>         "ar.saoodshuraym" to "سعود الشريم"
>     )
> ```
> 
> All Arabic names are obtained from http://mp3quran.net/.

I think it would be better to add Mujawwad like this (المجود)..
for example:
"Husary (Mujawwad)" to "(محمود خليل الحصري (المجود",
instead of "Husary (Mujawwad)" to "محمود خليل الحصري المجود",

**Comment by meezaan** [comment]
Done.
