### ISSUE TITLE
Audio Ayat incomplete

### ISSUE THREAD

**Issue by baroudihassan** [islamic-network/api.alquran.cloud#39]
The last ayat of surat An-nisaa is incomplete: https://cdn.alquran.cloud/media/audio/ayah/ar.alafasy/669/high

**Comment by meezaan** [comment]
Thank you for the issue. It appears to come back at the complete 58 seconds when I access it.

Can you please share the output of the following from where you are trying to query:

```
curl -I https://cdn.alquran.cloud/media/audio/ayah/ar.alafasy/669/high
```

Thank you.

**Comment by baroudihassan** [comment]
Yes now it's good, the problem is fixed
