### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by mrifni** [islamic-network/api.alquran.cloud#44]
I am getting Too Many Requests when i try to update a doc quran ayahs. Doc has almost 50 ayahs.

**Comment by meezaan** [comment]
Al Salaamu Alaykum @mrifni.

You are allowed 120 requests per minute per IP, so unless you are querying for multiple editions, 50 requests should be OK. If you want multiple editions, you can get them per ayah in one call.

Are these in any particular order, if so, I recommend trying the surah or juz endpoints.

Hope this helps?
