### ISSUE TITLE
More Arabic Translations

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/api.alquran.cloud#48]
The API is rich in non-Arabic translations however it's only featuring two Arabic Translations (تفسير الجلاين و الميسر)

**Comment by meezaan** [comment]
Al Salaamu Alaykum @vipafattal. I have also seen your email but I'm sorry have been unable to respond.

I don't have any digitised text of Arabic commentaries, but if you have access to some and permission to use, we can certainly add them to the API.

**Comment by vipafattal** [comment]
Never mind I just wanted to make sure that my message reached you.
Though I don't have any Arabic text with proper license to use I'm trying to reach [QuranAndroid](https://github.com/quran/quran_android/issues/1550) and [quranenc.com](https://quranenc.com/) for licensed Arabic translations.
