### ISSUE TITLE
Rename the misleading 'edition' to 'translation'

### ISSUE THREAD

**Issue by Kamrulhasan12345** [islamic-network/api.alquran.cloud#51]
Assalamu'alaikum wa rahmatullahi wa barakatuh,

Recently, I saw that the word 'edition' has been used instead of 'translation'. Infact, to non-muslims, it will look like them as different kinds of quran. I mean different edition of quran. We know, that Bible, and other books have different editions, but Quran is the one, and only. And we, muslims, are advised not to follow the culture of non-muslims. So, I think the misleading 'edition' should be renamed to 'edition'. It may look like a huge work. But its reward will save us from Jahannam. We should fix this issue.

JAK.

**Comment by meezaan** [comment]
Alaykum Salaam @Kamrulhasan12345.

Thank you for reaching out. There are not only translations available, but also some basic text from tafseer and, in fact, several editions of the text (quran-simple, quran-uthmani, quran-unicode and so on so forth).

No one is following the culture of non Muslims here. English is a language, and the word edition has a specific meaning to describe a version of a *published* text. It has nothing to do with the revealed nature of the Qur'an itself, and making that connection, as such, would be ignorance, and no amount of rewording can cure that.

I do appreciate your reaching out - in the end, God will decide who will go to Janna and who will go to jahnnam - and He knows best.

**Comment by Kamrulhasan12345** [comment]
Now understood what you said, and happy to hear that!
