### ISSUE TITLE
Calling any Arabic endpoint with language code will response always with `quran-simple`

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/api.alquran.cloud#53]
For example, calling the page endpoint on the `quran-wordbyword-2` edition will result in getting verses of a `quran-simple` see [page 2](https://api.alquran.cloud/v1/page/2/ar.quran-wordbyword-2).
 The issue is affecting all Arabic endpoints (not just page) see [verse 289](https://api.alquran.cloud/v1/ayah/289/ar.quran-wordbyword-2).

I'm not sure if this also would happen in the other languages.

**Comment by meezaan** [comment]
@vipafattal The edition identifier is incorrect. The edition identifier is quran-wordbyword-2, not ar.quran-wordbyword-2.

**Comment by vipafattal** [comment]
I understand, but don't you think @meezaan it's appropriate to return a response describing that you've reached an invalid endpoint such as [this](https://api.alquran.cloud/v1/edition?format=text&language=en&type=quran).

**Comment by meezaan** [comment]
This was done for legacy reasons, as the API used to return a default version.

Changing that would break some apps, and being a public API, I have no real idea about who the consumers are.

**Comment by meezaan** [comment]
Ideally, if you are programmatically retrieving the identifiers, you should never be passing an invalid identifier.

**Comment by vipafattal** [comment]
Okay I understand now
