### ISSUE TITLE
Ensure that “audio” URL is not repeated in “audioSecondary”

### ISSUE THREAD

**Issue by Sherbeeny** [islamic-network/api.alquran.cloud#54]

**Comment by meezaan** [comment]
This is now done. See https://api.alquran.cloud/v1/surah/1/ar.alafasy for instance.

**Comment by Sherbeeny** [comment]
Thank you!

For that file for example, I noticed that there's a CDN2 in the secondaryAudio but the 128 version URL in cdn2 is not included in the secondaryAudio.

**Comment by meezaan** [comment]
It's there.

```
"audio": "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1.mp3",
        "audioSecondary": [
          "https://cdn2.islamic.network/quran/audio/128/ar.alafasy/1.mp3",
          "https://cdn.islamic.network/quran/audio/64/ar.alafasy/1.mp3",
          "https://cdn2.islamic.network/quran/audio/64/ar.alafasy/1.mp3"
        ],
```

Or are you seeing something else?

**Comment by Sherbeeny** [comment]
Oh... My mistake then!
Thank you for your great efforts.
