### ISSUE TITLE
Some of the arabic surat name are returned with caracters 

### ISSUE THREAD

**Issue by belabdifatimazohra** [islamic-network/api.alquran.cloud#62]
![image](https://user-images.githubusercontent.com/10096682/162079182-c409e04c-eb79-4841-ad2c-f686a5b11cd4.png)

**Comment by meezaan** [comment]
This is related to either the browser or the font you are using, not with the API.

**Comment by belabdifatimazohra** [comment]
I used Google chrome for that. Thanks for your reply @meezaan
