### ISSUE TITLE
I create the java wrapper library for this awesome API 💙, And if you take a look at it and give me some of the notes this makes me happy ❤️

### ISSUE THREAD

**Issue by anas-elgarhy** [islamic-network/api.alquran.cloud#66]
Link: https://github.com/anas-elgarhy/alquran-cloud-api
And I have some notes also:
- If the `edition` object has a number of pages attribute, I think that is useful in times
- And the limit of requests I think it's short

**Comment by meezaan** [comment]
JazakAllah brother. I'll have a look, inshaAllah and can look at adding pagination. You mean the rate limit per second should be higher?
