### ISSUE TITLE
Asma husna API not working

### ISSUE THREAD

**Issue by tauntmachine** [islamic-network/api.alquran.cloud#67]
API -- http://api.aladhan.com/asmaAlHusna/

RESPONSE --- 
{
    "code": 404,
    "status": "RESOURCE_NOT_FOUND",
    "message": "Not found.",
    "trace": "#0 \/var\/www\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(58): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(Slim\\Psr7\\Request))\n#1 \/var\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process(Object(Slim\\Psr7\\Request), Object(Slim\\Routing\\RouteRunner))\n#2 \/var\/www\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(Slim\\Psr7\\Request))\n#3 \/var\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process(Object(Slim\\Psr7\\Request), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#4 \/var\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(Slim\\Psr7\\Request))\n#5 \/var\/www\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle(Object(Slim\\Psr7\\Request))\n#6 \/var\/www\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle(Object(Slim\\Psr7\\Request))\n#7 \/var\/www\/html\/index.php(20): Slim\\App->run()\n#8 {main}"
}

**Comment by basit3407** [comment]
Same here. It's not giving response any more

**Comment by meezaan** [comment]
Please us v1. These URLs were deprecated in 2017, but it looks like I missed updating the docs and adding a 301.

http://api.aladhan.com/v1/asmaAlHusna

I'll make the updates.

**Comment by tauntmachine** [comment]
JazakAllah
