### ISSUE TITLE
Wrong word in Ayah 127 in verse number 2

### ISSUE THREAD

**Issue by tkyr-hh** [islamic-network/api.alquran.cloud#69]
The API: https://api.alquran.cloud/v1/page/20/quran-uthmani
![Screenshot 2022-11-15 at 8 59 30 PM](https://user-images.githubusercontent.com/96578305/202015054-11f2c3a7-440a-4735-9db3-471bd642b928.png)
the word `ابراهيم` is wrong

**Comment by meezaan** [comment]
What is wrong with it?

**Comment by tkyr-hh** [comment]
the word `ابراهيم` is wrong

**Comment by meezaan** [comment]
No, it's fine. You need to use a font that can display Qur'anic Arabic. There is a difference between Classical Arabic and modern  Arabic, and then there are some words that are sometimes written differently in Qur'anic Arabic.

Rendered properly, this is how it appears - https://alquran.cloud/ayah/2:127.

And here is an image of how it appears in printed Qur'ans - http://cdn.islamic.network/quran/images/2_127.png.

**Comment by tkyr-hh** [comment]
Thanks a lot @meezaan  for your reply. Can you please share with me the Quran's Font used in the link above??

**Comment by meezaan** [comment]
> Thanks a lot @meezaan for your reply. Can you please share with me the Quran's Font used in the link above??

https://alquran.cloud/public/css/font-kitab.css?v=1

**Comment by tkyr-hh** [comment]
@meezaan Jazak ALLAH khayr
