### ISSUE TITLE
Major error in API response

### ISSUE THREAD

**Issue by faisalamin001** [islamic-network/api.alquran.cloud#70]
I only checked the first surah and found two mistakes in verses. kindly review these strings.

Incorrect words:
Surah 1 verse 1 : رَبِّ 
Surah 1 verse 5 : ٱلصِّرَ ٰ⁠طَ

<img width="264" alt="Screenshot 2023-03-21 at 7 04 27 PM" src="https://user-images.githubusercontent.com/58821374/226635845-034aec51-8923-432d-aef3-8c18df3a0b19.png">

**Comment by meezaan** [comment]
> I only checked the first surah and found two mistakes in verses. kindly review these strings.
> 
> 
> 
> Incorrect words:
> 
> Surah 1 verse 1 : رَبِّ 
> 
> Surah 1 verse 5 : ٱلصِّرَ ٰ⁠طَ
> 
> 
> 
> <img width="264" alt="Screenshot 2023-03-21 at 7 04 27 PM" src="https://user-images.githubusercontent.com/58821374/226635845-034aec51-8923-432d-aef3-8c18df3a0b19.png">
> 
> 

You want to elaborate on why you think there is a problem?

**Comment by faisalamin001** [comment]
Isn't it Kasra [ ِ] in **رَبِّ** word instead of fatha [ َ]?

**Comment by meezaan** [comment]
It is a kasra. It can be written below the shadda or below the ba, depending on the script. Both are correct. It would be incorrect if it was above the shadda - then it would count as fatha.
