### ISSUE TITLE
Doesn't display cyrillic characters correctly

### ISSUE THREAD

**Issue by knull-a** [islamic-network/api.alquran.cloud#76]
Get unicode instead of letters. For example: \u0420\u0435\u0433\u0438\u043e\u043d
https://api.alquran.cloud/v1/quran/ru.kuliev

**Comment by meezaan** [comment]
> Get unicode instead of letters. For example: \u0420\u0435\u0433\u0438\u043e\u043d
> 
> https://api.alquran.cloud/v1/quran/ru.kuliev

This is the correct behaviour to avoid any encoding issues. You will have to 'unescape' the Unicode and it will work just fine.
