### ISSUE TITLE
How to use search function to search with arabic not english?

### ISSUE THREAD

**Issue by AbdelrhmanUZaki** [islamic-network/api.alquran.cloud#80]

**Comment by AbdelrhmanUZaki** [comment]
http://api.alquran.cloud/v1/search/{{keyword}}/{{surah}}/{{edition or language}}
sorry for asking here instead of community, it was a mistake..

**Comment by meezaan** [comment]
Answered on https://community.islamic.network/d/74-how-to-use-search-function-to-search-in-arabic.
