### ISSUE TITLE
Get & Parse Tajweed

### ISSUE THREAD

**Issue by akbarjorayev** [islamic-network/api.alquran.cloud#82]
How can I do that in JavaScript? [Link](https://alquran.cloud/tajweed-guide)

**Comment by akbarjorayev** [comment]
@meezaan Can you help me?

**Comment by meezaan** [comment]
> @meezaan Can you help me?

I don't know of anything in Vanilla JS. There's a React package - https://github.com/aamirbhat382/Tajweed and an Android one https://github.com/vipafattal/TajweedParser - but these are the only 2 I know of besides the PHP one in this repo.

**Comment by akbarjorayev** [comment]
> > @meezaan Can you help me?
> 
> I don't know of anything in Vanilla JS. There's a React package - https://github.com/aamirbhat382/Tajweed and an Android one https://github.com/vipafattal/TajweedParser - but these are the only 2 I know of besides the PHP one in this repo.

I use your API in this [Quran App](https://quran-app-id.web.app/) Can you help me to make Quran in tajweed (to make colorful). Like in this Quranly app:
![image](https://github.com/islamic-network/api.alquran.cloud/assets/100585930/42afdf42-47eb-4710-977c-e8b0bf20ce9b)

**Comment by meezaan** [comment]
I do not have time to contribute code, I'm afraid.

**Comment by akbarjorayev** [comment]
Ok

> I do not have time to contribute code, I'm afraid.

I understand 👌
