### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Faiyyaz** [islamic-network/api.alquran.cloud#84]
Assalam walekum,

Thank you for such a great api.

I was building an android app using your api but I have a query in the kids quran.

If you see the below text there are some numbers after the arabic letters.

بِسْمِ|In (the) name|112|146|1$ٱللَّهِ|(of) Allah,|86|153|2$ٱلرَّحْمَـٰنِ|the Most Gracious,|145|212|3$ٱلرَّحِيمِ|the Most Merciful.|140|174|4$

Can you let me know the meaning of those numbers?

Jazak Allah

**Comment by meezaan** [comment]
3laykym salaam Faiyyaz. This is a good question - I have no idea.

This edition was imported from from the GlobalQuran project (https://github.com/GlobalQuran) almost 10 years ago, so it may be worth asking someone there.

**Comment by Faiyyaz** [comment]
@meezaan Jazak Allah. I will raise the query on that repository.
