### ISSUE TITLE
Issue regarding missing first ayah of multiple juzz's

### ISSUE THREAD

**Issue by Aliyan-Ansari** [islamic-network/api.alquran.cloud#85]
let's take this API for reference 
http://api.alquran.cloud/v1/juz/21/quran-uthmani
it return the first ayah as:
 '  وَ لَا تُجَادِلُوْۤا اَهْلَ الْكِتٰبِ اِلَّا بِالَّتِیْ هِیَ اَحْسَنُ ﳓ اِلَّا الَّذِیْنَ ظَلَمُوْا مِنْهُمْ وَ قُوْلُوْۤا اٰمَنَّا بِالَّذِیْۤ اُنْزِلَ اِلَیْنَا وَ اُنْزِلَ اِلَیْكُمْ وَ اِلٰهُنَا وَ اِلٰهُكُمْ وَاحِدٌ وَّ نَحْنُ لَهٗ مُسْلِمُوْنَ'
But, if you check Quran for Juzz 21 it starts with:
'اُتْلُ مَاۤ اُوْحِیَ اِلَیْكَ مِنَ الْكِتٰبِ وَ اَقِمِ الصَّلٰوةَؕ-اِنَّ الصَّلٰوةَ تَنْهٰى عَنِ الْفَحْشَآءِ وَ الْمُنْكَرِؕ-وَ لَذِكْرُ اللّٰهِ اَكْبَرُؕ-وَ اللّٰهُ یَعْلَمُ مَا تَصْنَعُوْنَ '.
For reference i have also attached correct version of it
https://www.dawateislami.net/quran/para-21

**Comment by meezaan** [comment]
dawateislami is not an official source of the Qur'an. 

Some sub-continent Qur'ans often differ from the Madina mushaf by one ayah when marking the juz, so this is not a problem with the API as this has been checked in printed Quran's and matches the ayahs in a juz on several other online sources.
