### ISSUE TITLE
Koran.center release / Quran.meta

### ISSUE THREAD

**Issue by husayt** [islamic-network/api.alquran.cloud#86]
Salam aleykum. Sorry in advance, for posting here. Would be good to have discussions section for this kind of messages in future.

Since we use api.alquran.cloud for our audio sources and original quran text at Koran.center  I wanted to share news of our latest release here, with our thanks:

Also, in return we want to share the useful functionality, which could be useful to fellow Quran app developers and have released a new version of Quran Meta library, which is a fully test covered and has a number of key features.  Hope you will find it useful. We are happy to add more features to make it even more useful. we will be extracting more of Koran.center functionality into reusable libraries. Let us know what will be of value.

Quran Meta Library
https://github.com/quran-center/quran-meta

**Koran.Center Release Announcement:** 

We’re excited to announce the release of version 8.6.x, bringing new features and improvements:
	• Discover the Prophets Mentioned in the Quran on our newly added page.
	• Updated Translation: We’ve integrated the latest Elmir Kuliyev translation (2024).
	• User Experience Enhancements: A default language check and a Release Notes page keep you informed and simplify usage.
	• Quick Access to Prayer Times: Direct link to Salah.com for convenience.

Fixes & Improvements:
	• Enhanced formatting for Parables and Stories
	• Translations added for missing labels, search functionality upgraded, and fonts updated for better readability.
	• Hundreds of small fixes and improvements

Explore these updates for a smoother, more informative experience!

https://koran.center/en

**Comment by meezaan** [comment]
3laykum salaam @husayt. Thank you for sharing - I suggest using https://community.islamic.network for discussions like this.

**Comment by husayt** [comment]
that is exactly what I was looking for @meezaan 


Thank you for all the amazing and useful resources you have here

**Comment by meezaan** [comment]
Discussion moved to https://community.islamic.network/d/89-quran-text-verification-framework.
